version: '2'
services:

  # ------------------------------------------------------------------------
  # Shared base layer services
  # ------------------------------------------------------------------------
  
  # -------------------------------------
  # Mariadb

  mariadb:
    image: mariadb:10
    volumes:
     - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: localdevonly


  # ------------------------------------------------------------------------
  # Web applications
  # ------------------------------------------------------------------------

  # -------------------------------------
  # Tokenpass

  tokenpass:
    image: tokenly/devtokenpass
    links:
      - mariadb:db
    depends_on:
      - mariadb
    ports:
     - "8000:80"
    environment:
      DB_HOST: db
      DB_USERNAME: tokenly
      DB_PASSWORD: tokenlydevpassword
      DB_DATABASE: tokenly_tokenpass_dev
      GITHUB_BRANCH: development
      # GITHUB_BRANCH: sassified
      PLATFORM_ADMIN_DEVELOPMENT_MODE_ENABLED: "true"

    volumes:
     - ./projects/tokenpass:/app/current
     - ./etc/tokenpass/etc/php5/fpm:/etc/php5/fpm

